/*
 * This file is generated by jOOQ.
 */
package org.bithon.demo.user.service.db.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private String name;
    private String password;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.name = value.name;
        this.password = value.password;
    }

    public User(
        Long   id,
        String name,
        String password
    ) {
        this.id = id;
        this.name = name;
        this.password = password;
    }

    /**
     * Getter for <code>user.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>user.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>user.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>user.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>user.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>user.password</code>.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(password);

        sb.append(")");
        return sb.toString();
    }
}
