server:
  port: 29525

bithon:
  demo:
    gateway:
      targetServer: localhost

spring:
  application:
    name: bithon-demo-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          predicates:
            - Path=/api/user/**
          uri: http://${bithon.demo.gateway.targetServer}:29526
        - id: system-service
          predicates:
            - Path=/api/system/**
          uri: http://${bithon.demo.gateway.targetServer}:29526