#
#   Copyright 2020 bithon.org
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

# Build
ARG JDK=17
FROM maven:3.9.5-amazoncorretto-${JDK}-debian-bookworm as builder
COPY . /src
WORKDIR /src
RUN --mount=type=cache,target=/root/.m2 \
      mvn -pl account-client -am \
      clean package \
      -DskipTests

FROM bithon/agent:latest as agent

FROM amazoncorretto:17.0.9-alpine3.18
COPY --from=builder /src/account-client/target/account-client.jar /opt/account-client.jar
COPY --from=agent /opt/agent-distribution /opt/agent-distribution

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

COPY docker/startup.sh /startup.sh
RUN chmod +x /startup.sh

ENV JAVA_OPTS ""
ENV APP_OPTS ""

WORKDIR /opt
ENTRYPOINT ["/startup.sh", "bithon-demo-account-client", "live", "account-client.jar"]
