/*
 * This file is generated by jOOQ.
 */
package org.bithon.demo.user.service.db.jooq;


import org.bithon.demo.user.service.db.jooq.tables.User;
import org.bithon.demo.user.service.db.jooq.tables.records.UserRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_PRIMARY"), new TableField[] { User.USER.ID }, true);
    public static final UniqueKey<UserRecord> KEY_USER_UQ_NAME = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_uq_name"), new TableField[] { User.USER.NAME }, true);
}
